"""The OpenAPI 3.1 document of the digital twin API, built from the route
table (koi/api/spec.py) and the pydantic request and response models.

    python -m koi.api.openapi            # rewrite docs/api/openapi.yaml
    python -m koi.api.openapi --check    # exit 1 if the committed file is out of date

tests/api/test_openapi.py fails when the committed document differs from
the one built here, so a change to a route or a model must be committed
with the regenerated file. The comparison is on the parsed document, so
YAML formatting does not matter. Writing and checking need PyYAML (a dev
dependency); building the document does not.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, Literal, Optional

from pydantic import BaseModel
from pydantic.json_schema import models_json_schema

from koi.api import responses
from koi.api.spec import OPERATIONS, Operation, openapi_path

DOCUMENT = Path(__file__).resolve().parents[3] / "docs" / "api" / "openapi.yaml"
REF = "#/components/schemas/{model}"

_STATUS_TEXT = {200: "OK", 201: "Created", 304: "Not modified", 400: "Invalid request", 401: "Not signed in",
                403: "Another account's pond", 404: "Pond or assessment not found", 409: "Conflict",
                422: "Not enough history to project", 503: "Storage or service not available"}

_DESCRIPTION = """\
Digital twin API of OutdoorKoi: pond chemistry, evaporation and algae.

Every route is served under /v1. The old unversioned paths are deprecated
aliases of their /v1 route (same response, plus `Deprecation` and, where the
/v1 path can be built, `Link: rel="successor-version"`); they are removed
once the app calls /v1. /health and /ready are also served unversioned,
without deprecation, for probes. /metrics is Prometheus text.

GET responses with a JSON body carry a strong `ETag` and
`Cache-Control: private, no-cache`; send it back in `If-None-Match` to get
304 with no body when nothing in the response has changed. Freshness is
part of the body, so a reading going stale changes the ETag.

Every non-2xx response is the ErrorEnvelope. Generated by
`python -m koi.api.openapi` from Backend/koi/api; do not edit by hand.
Field rules for the dashboard: docs/api/README.md.
"""


Mode = Literal["validation", "serialization"]


def _models() -> list[tuple[type[BaseModel], Mode]]:
    seen: dict[tuple[type[BaseModel], Mode], None] = {(responses.ErrorEnvelope, "serialization"): None}
    for op in OPERATIONS:
        for model in op.responses.values():
            if model is not None:
                seen[(model, "serialization")] = None
        if op.body is not None:
            seen[(op.body, "validation")] = None
    return list(seen)


def _parameters(op: Operation) -> list[dict]:
    params: list[dict] = []
    if "<int:user_id>" in op.rule:
        name = openapi_path(op.rule).split("{")[1].split("}")[0]
        params.append({"name": name, "in": "path", "required": True,
                       "description": "The pond (UserData.userID); must be the signed-in account's pond.",
                       "schema": {"type": "integer", "minimum": 0}})
    if op.query is not None:
        schema = op.query.model_json_schema(ref_template=REF)
        required = set(schema.get("required", []))
        for name, prop in schema.get("properties", {}).items():
            params.append({"name": name, "in": "query", "required": name in required, "schema": prop})
    return params


def _responses(op: Operation, refs: dict[tuple[type[BaseModel], Mode], dict]) -> dict:
    out: dict[str, Any] = {}
    for status, model in op.responses.items():
        entry: dict[str, Any] = {"description": _STATUS_TEXT.get(status, "OK")}
        if model is not None:
            entry["content"] = {"application/json": {"schema": refs[(model, "serialization")]}}
        if op.method == "GET":
            entry["headers"] = {"ETag": {"description": "Strong validator over the response body.",
                                         "schema": {"type": "string"}},
                                "Cache-Control": {"schema": {"type": "string", "const": "private, no-cache"}}}
        if op.deprecated:
            entry.setdefault("headers", {})["Deprecation"] = {
                "description": "RFC 9745: the date this path was deprecated.", "schema": {"type": "string"}}
        out[str(status)] = entry
    if op.method == "GET":
        out["304"] = {"description": "Not modified: If-None-Match matches the current ETag. No body."}
    error = {"application/json": {"schema": refs[(responses.ErrorEnvelope, "serialization")]}}
    for status in sorted(set(op.errors) | {500}):
        out[str(status)] = {"description": _STATUS_TEXT.get(status, "Unexpected server error"), "content": error}
    return out


def _operation(op: Operation, refs: dict) -> dict:
    entry: dict[str, Any] = {"operationId": op.endpoint, "summary": op.summary, "tags": [op.tag]}
    if op.description:
        entry["description"] = " ".join(op.description.split())
    if op.deprecated:
        entry["deprecated"] = True
        entry["description"] = (f"Deprecated alias of {openapi_path(op.successor or '')}. "
                                + entry.get("description", "")).strip()
    params = _parameters(op)
    if op.method == "GET":
        params.append({"name": "If-None-Match", "in": "header", "required": False,
                       "description": "An ETag from an earlier response.", "schema": {"type": "string"}})
    if params:
        entry["parameters"] = params
    if op.body is not None:
        entry["requestBody"] = {"required": True,
                                "content": {"application/json": {"schema": refs[(op.body, "validation")]}}}
    entry["responses"] = _responses(op, refs)
    entry["security"] = [{"bearerAuth": []}] if op.auth else []
    return entry


def build_document() -> dict:
    """The OpenAPI document as a dict (JSON types only)."""
    import koi.api.routes  # noqa: F401 - registers every route in OPERATIONS

    models = _models()
    refs, defs = models_json_schema(models, ref_template=REF)
    paths: dict[str, dict] = {}
    for op in OPERATIONS:
        paths.setdefault(openapi_path(op.rule), {})[op.method.lower()] = _operation(op, refs)
    paths["/metrics"] = {"get": {
        "operationId": "metrics", "summary": "Prometheus metrics", "tags": ["service"], "security": [],
        "responses": {"200": {"description": "Prometheus text exposition format.",
                              "content": {"text/plain": {"schema": {"type": "string"}}}}}}}
    return {
        "openapi": "3.1.0",
        "info": {"title": "OutdoorKoi digital twin API", "version": "1", "description": _DESCRIPTION},
        "servers": [{"url": "/"}],
        "tags": [{"name": t} for t in ("pond", "assessments", "forecasts", "events", "ratings", "service")],
        "paths": {p: paths[p] for p in sorted(paths)},
        "components": {
            "schemas": {name: defs["$defs"][name] for name in sorted(defs.get("$defs", {}))},
            "securitySchemes": {"bearerAuth": {"type": "http", "scheme": "bearer", "bearerFormat": "JWT",
                                               "description": "The Supabase access token of the pond's account."}},
        },
    }


def schema_for(model: type[BaseModel], document: Optional[dict] = None) -> dict:
    """A component schema by model name, with $refs resolvable against
    the document (for jsonschema)."""
    document = document or build_document()
    return {"$ref": REF.format(model=model.__name__), "components": document["components"]}


def render(document: dict) -> str:
    import yaml

    return yaml.safe_dump(document, sort_keys=False, allow_unicode=True, width=100)


def load(path: Path = DOCUMENT) -> dict:
    import yaml

    return yaml.safe_load(path.read_text(encoding="utf-8"))


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="exit 1 if the committed document is out of date")
    args = parser.parse_args(argv)
    document = build_document()
    if args.check:
        if not DOCUMENT.exists() or load() != document:
            sys.stderr.write(f"{DOCUMENT} is out of date; run python -m koi.api.openapi\n")
            return 1
        return 0
    DOCUMENT.parent.mkdir(parents=True, exist_ok=True)
    DOCUMENT.write_text(render(document), encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
