-- 0001_baseline.sql
--
-- Baseline of the OutdoorKoi Supabase schema, reconstructed from how the
-- code in this repository reads and writes the database:
--   Backend/DigitalTwin/state_store.py   (digital twin service)
--   Backend/Camera/camera.py             (camera service)
--   Embedded/sensor_node/sensor_node.ino (ESP32 sensor node)
--   MobileUI/mobile_app/lib/             (Flutter app)
--
-- Until this file existed the schema lived only in the live project. Table
-- and column names are copied exactly from the code, including the three
-- spellings of the user column ("userID", "user_ID", userid) that coexist
-- in the live schema; quoted identifiers are case-sensitive, so do not
-- normalise them here without a migration that also changes every reader.
--
-- Anything that could not be recovered from the code is marked
--   -- RECONSTRUCTED: verify against live
-- The owner diffs this file against the live project (see
-- supabase/README.md) and records the differences in a later migration.
--
-- Not covered by this baseline (live-only, not recoverable from code):
--   * Row-level security policies and grants. The app and the sensor node
--     use the publishable (anon) key to read and write UserData,
--     pondInterventions, Fish_Database, imageTable and SensorData, and to
--     call both RPCs, so the live policies must allow at least that.
--   * The job that fetches NEA weather into weather_telemetry and
--     weather_forecasts, and any pg_cron schedules.
--
-- Every statement is idempotent (IF NOT EXISTS / OR REPLACE / ON CONFLICT)
-- so the file can be applied to a fresh project or replayed against one
-- that already has the tables without error.

-- =====================================================================
-- Telemetry from the ESP32 sensor node
-- =====================================================================

-- One row per reading. The sensor node inserts all readings from one wake
-- cycle as a single batched insert: [{sensor_type, data1}, ...] with
-- sensor_type in 'temp', 'TDS', 'pH', 'LUX'. LUX is -1 when the light
-- sensor failed that cycle.
-- RECONSTRUCTED: verify against live. The firmware sends no pond or user
-- id, so this table has no user column and every reader treats it as the
-- one instrumented pond. If the live table has a user column, add it here.
create table if not exists public."SensorData" (
    id          bigint generated by default as identity primary key,
    created_at  timestamptz not null default now(),
    sensor_type text not null,
    data1       double precision
);

create index if not exists "SensorData_type_created_idx"
    on public."SensorData" (sensor_type, created_at desc);

-- Daily aggregates of SensorData, one row per user, sensor type and UTC
-- calendar day. Read by state_store.fetch_daily_sensor_stats and
-- fetch_daily_sensor_series, and by get_historical_graph_payload.
create table if not exists public.daily_sensor_averages (
    id          bigint generated by default as identity primary key,
    userid      bigint not null,
    sensor_type text not null,
    avg_value   double precision,
    min_value   double precision,
    max_value   double precision,
    record_date date not null,
    unique (userid, sensor_type, record_date)
);

-- =====================================================================
-- Pond configuration and species reference data
-- =====================================================================

-- One row per pond owner, written at onboarding (onboarding_screen.dart
-- upserts on "userID") and deleted from settings. volume is litres,
-- biomass is kilograms of fish summed over every species entry.
create table if not exists public."UserData" (
    "userID"             bigint primary key,
    created_at           timestamptz not null default now(),
    volume               double precision,
    biomass              double precision,
    latitude             double precision,
    longitude            double precision,
    manualpostallocation text,
    -- Nearest NEA station per weather metric, filled by the trigger below
    -- and returned to the app by the onboarding upsert.
    "ClosestStations"    jsonb
);

-- Species care data shown in the app's species guide. Columns match the
-- AquariumScraper CSV the table was loaded from; every value is free text
-- (ranges such as '6.0 - 7.0' and '21°C - 26°C' are parsed in the app).
create table if not exists public."Fish_Database" (
    "Title"        text primary key,
    "Product URL"  text,
    "Image URL"    text,
    "Common Name"  text,
    "Care Level"   text,
    "Maximum Size" text,
    "pH"           text,
    "Temperature"  text,
    "Life Span"    text,
    "Behaviour"    text,
    "Tank Region"  text,
    "Gender"       text
);

-- =====================================================================
-- Owner-logged interventions
-- =====================================================================

-- event_type values are upper snake case: 'FEEDING', 'WATER_CHANGE',
-- 'WATER_TOPUP', 'ALGAE_SCRUB'. Only the columns for the logged type are
-- filled; the rest stay null.
create table if not exists public."pondInterventions" (
    id                 bigint generated by default as identity primary key,
    created_at         timestamptz not null default now(),
    "userID"           bigint not null,
    event_type         text not null,
    event_timestamp    timestamptz not null default now(),
    volume_percentage  double precision,
    volume_litres      double precision,
    food_grams         double precision,
    protein_percentage double precision,
    algae_method       text
);

create index if not exists "pondInterventions_user_type_ts_idx"
    on public."pondInterventions" ("userID", event_type, event_timestamp desc);

-- =====================================================================
-- Camera frames
-- =====================================================================

-- One row per analysed ESP32-CAM frame, written by Backend/Camera/camera.py.
-- current_state is the HSV state machine's output, normally a two-element
-- array like ["base", 0.1235] (label, smoothed green-ratio baseline).
-- imageURL is the public URL of the frame in the imageAnalysisBucket bucket.
-- RECONSTRUCTED: verify against live. "user_ID" is typed bigint to match
-- the other user columns; camera.py falls back to the string
-- 'default_user' when the X-User-ID header is missing, which a bigint
-- column rejects. If the live column is text, change it here.
create table if not exists public."imageTable" (
    id            bigint generated by default as identity primary key,
    created_at    timestamptz not null default now(),
    "user_ID"     bigint,
    green_ratio   double precision,
    current_state jsonb,
    "imageURL"    text
);

create index if not exists "imageTable_user_created_idx"
    on public."imageTable" ("user_ID", created_at desc);

-- Human algae severity labels from the app's rating card.
-- green_ratio_at_rating is copied from the frame so the calibration set
-- survives imageTable rows being pruned; image_id is cleared rather than
-- the rating deleted when that happens.
-- severity is one of 'none', 'minor', 'moderate', 'severe' or
-- 'obstruction' (algae_engine.SEVERITY_LEVELS plus the blocked-view flag).
create table if not exists public.algae_severity_ratings (
    id                    bigint generated by default as identity primary key,
    userid                bigint not null,
    image_id              bigint references public."imageTable" (id) on delete set null,
    image_url             text,
    severity              text not null,
    is_obstructed         boolean not null default false,
    green_ratio_at_rating double precision,
    image_captured_at     timestamptz,
    rated_at              timestamptz not null default now(),
    notes                 text
);

create index if not exists algae_severity_ratings_user_rated_idx
    on public.algae_severity_ratings (userid, rated_at desc);

-- =====================================================================
-- NEA weather
-- =====================================================================

-- RECONSTRUCTED: verify against live. No code in this repository writes
-- these two tables; a live-only job fetches the data.gov.sg real-time
-- weather APIs into them. The shapes below are what
-- get_bundled_dashboard_payload needs to produce the keys the poller and
-- the app read.

-- Latest station readings. metric is 'air_temp', 'rainfall', 'wind_speed'
-- or 'relative_humidity'. value is in the NEA API's own unit (°C, mm,
-- knots, %).
create table if not exists public.weather_telemetry (
    id           bigint generated by default as identity primary key,
    recorded_at  timestamptz not null,
    fetched_at   timestamptz not null default now(),
    metric       text not null,
    station_id   text not null,
    station_name text,
    latitude     double precision,
    longitude    double precision,
    value        double precision,
    unique (metric, station_id, recorded_at)
);

create index if not exists weather_telemetry_metric_recorded_idx
    on public.weather_telemetry (metric, recorded_at desc);

-- Latest forecasts, one row per fetch. forecast_type is 'forecast_2hr',
-- 'forecast_24hr', 'outlook_4day' or 'uv_index'. payload holds the value
-- handed to the app unchanged:
--   forecast_2hr   {"area": ..., "forecast": "Fair (Day)"}, one row per area
--   forecast_24hr  {"general": {...}, "periods": [...]}
--   outlook_4day   [{"data": {"day", "forecast", "temperature", ...}}, ...]
--   uv_index       {"data": {"uv": 5, ...}}
-- area is set only for forecast_2hr.
create table if not exists public.weather_forecasts (
    id            bigint generated by default as identity primary key,
    fetched_at    timestamptz not null default now(),
    forecast_type text not null,
    area          text,
    valid_from    timestamptz,
    valid_to      timestamptz,
    payload       jsonb not null
);

create index if not exists weather_forecasts_type_fetched_idx
    on public.weather_forecasts (forecast_type, fetched_at desc);

-- =====================================================================
-- Digital twin state and evaluations (written by Backend/DigitalTwin)
-- =====================================================================

-- One persisted engine snapshot per pond. The snapshot shape is versioned
-- by the engine, not by this table.
create table if not exists public.pond_chemistry_state (
    user_id    bigint primary key,
    snapshot   jsonb not null,
    updated_at timestamptz not null default now()
);

-- Chemistry assessment log, appended every poll and every event. There is
-- deliberately no risk_score column and no unique (userid, evaluated_at).
create table if not exists public.pond_chemistry_evaluations (
    id               bigint generated by default as identity primary key,
    userid           bigint not null,
    evaluated_at     timestamptz not null default now(),
    status           text not null,
    category         text not null,
    tan_ppm          double precision,
    no2_ppm          double precision,
    no3_ppm          double precision,
    ph_reactivity    double precision,
    reactivity_trend double precision,
    tds_trend        double precision,
    sensor_warnings  jsonb not null default '[]'::jsonb,
    advisory         text,
    add_hardener_now boolean not null default false
);

create index if not exists pond_chemistry_evaluations_user_eval_idx
    on public.pond_chemistry_evaluations (userid, evaluated_at desc);

-- Evaporation assessment log. Units: litres, percent of pond volume,
-- mm/day, litres/day, °C, grams of feed; days_to_topup is whole days.
create table if not exists public.pond_evaporation_evaluations (
    id                     bigint generated by default as identity primary key,
    userid                 bigint not null,
    evaluated_at           timestamptz not null default now(),
    status                 text not null,
    category               text not null,
    loss_litres            double precision,
    loss_pct               double precision,
    evaporation_mm_per_day double precision,
    loss_litres_per_day    double precision,
    water_temp_c           double precision,
    feed_cap_grams         double precision,
    feed_note              text,
    days_to_topup          integer,
    advisory               text,
    topup_now              boolean not null default false
);

create index if not exists pond_evaporation_evaluations_user_eval_idx
    on public.pond_evaporation_evaluations (userid, evaluated_at desc);

-- Algae assessment log.
create table if not exists public.pond_algae_evaluations (
    id                     bigint generated by default as identity primary key,
    userid                 bigint not null,
    evaluated_at           timestamptz not null default now(),
    status                 text not null,
    category               text not null,
    green_ratio            double precision,
    watch_threshold        double precision,
    action_threshold       double precision,
    threshold_mode         text,
    growth_rate_per_day    double precision,
    intrinsic_rate_per_day double precision,
    rate_source            text,
    confidence             text,
    sample_count           integer,
    days_to_scrub          integer,
    advisory               text,
    scrub_now              boolean not null default false
);

create index if not exists pond_algae_evaluations_user_eval_idx
    on public.pond_algae_evaluations (userid, evaluated_at desc);

-- =====================================================================
-- Storage buckets
-- =====================================================================

-- imageAnalysisBucket: ESP32-CAM frames, object path
--   "{user_id}/{unix_seconds}_photo.jpg", written by camera.py and read by
--   the app through public URLs (POND_IMAGE_BUCKET on both sides).
-- pond-images: owner-uploaded species photos, object path
--   "{user_id}/{Species_Title}_{timestamp}.jpg", written by the app.
-- RECONSTRUCTED: verify against live (public flag, size and MIME limits).
insert into storage.buckets (id, name, public)
values ('imageAnalysisBucket', 'imageAnalysisBucket', true),
       ('pond-images', 'pond-images', true)
on conflict (id) do nothing;

-- =====================================================================
-- Functions and triggers
-- =====================================================================

-- Fills UserData."ClosestStations" with the nearest NEA station for each
-- weather metric, from the pond's latitude and longitude, so the dashboard
-- payload can read the readings nearest the pond. Result shape:
--   {"air_temp": "S109", "rainfall": "S77", ..., "forecast_area": "Bishan"}
-- RECONSTRUCTED: verify against live. The app only shows that a JSON
-- object comes back from the onboarding upsert; the key names, the
-- distance measure and the forecast_area lookup are written from that
-- documented behaviour.
create or replace function public.assign_closest_stations()
returns trigger
language plpgsql
as $$
declare
    stations jsonb;
begin
    if new.latitude is null or new.longitude is null then
        new."ClosestStations" := null;
        return new;
    end if;

    -- Equirectangular distance is accurate enough across Singapore.
    select jsonb_object_agg(metric, station_id)
      into stations
      from (
        select distinct on (metric) metric, station_id
          from public.weather_telemetry
         where latitude is not null and longitude is not null
         order by metric,
                  power(latitude - new.latitude, 2)
                  + power((longitude - new.longitude) * cos(radians(new.latitude)), 2),
                  recorded_at desc
      ) nearest;

    new."ClosestStations" := coalesce(stations, '{}'::jsonb)
        || jsonb_build_object('forecast_area', (
            select f.area
              from public.weather_forecasts f
             where f.forecast_type = 'forecast_2hr'
               and f.area is not null
               and f.payload ? 'latitude'
             order by power((f.payload ->> 'latitude')::double precision - new.latitude, 2)
                      + power(((f.payload ->> 'longitude')::double precision - new.longitude)
                              * cos(radians(new.latitude)), 2),
                      f.fetched_at desc
             limit 1));
    return new;
end;
$$;

drop trigger if exists "UserData_assign_closest_stations" on public."UserData";
create trigger "UserData_assign_closest_stations"
    before insert or update of latitude, longitude on public."UserData"
    for each row execute function public.assign_closest_stations();

-- Recomputes one UTC day of daily_sensor_averages from SensorData for
-- every onboarded pond. LUX readings of -1 (failed light sensor) are
-- excluded.
-- RECONSTRUCTED: verify against live. The code documents only that rows
-- are daily aggregates by UTC calendar day with gaps when the sensor was
-- offline. Because SensorData carries no user id, every pond in UserData
-- gets the same aggregate. How the live project schedules this (pg_cron,
-- trigger or external job) is not recoverable from the code.
create or replace function public.refresh_daily_sensor_averages(p_day date)
returns void
language sql
as $$
    insert into public.daily_sensor_averages
        (userid, sensor_type, avg_value, min_value, max_value, record_date)
    select u."userID", s.sensor_type, avg(s.data1), min(s.data1), max(s.data1), p_day
      from public."SensorData" s
     cross join public."UserData" u
     where s.created_at >= p_day::timestamp at time zone 'UTC'
       and s.created_at <  (p_day + 1)::timestamp at time zone 'UTC'
       and s.data1 is not null
       and not (s.sensor_type = 'LUX' and s.data1 < 0)
     group by u."userID", s.sensor_type
    on conflict (userid, sensor_type, record_date) do update
        set avg_value = excluded.avg_value,
            min_value = excluded.min_value,
            max_value = excluded.max_value;
$$;

-- Everything the dashboard and the digital twin poller need in one call.
-- Keys read by code:
--   raw_sensor        {pH, TDS, temp, LUX, recorded_at}
--                     poller.py, forecast_utils.current_conditions, the
--                     three dashboard cards
--   nea_telemetry     {air_temp, rainfall, wind_speed, relative_humidity},
--                     each {value, station_id, recorded_at}
--                     forecast_utils.current_conditions, weather ribbon,
--                     temperature card
--   nea_forecasts     {forecast_2hr, forecast_24hr, outlook_4day, uv_index,
--                      two_hr_forecast, rainfall_mm}
--                     forecast_utils, weather ribbon, forecast modal, pH and
--                     solar cards
--   telemetry_history [{time, ph, tds, tempC, lux}], oldest first
--                     dashboard_view._parseTelemetryHistory
-- The conftest.py DASHBOARD_PAYLOAD fixture is a recorded example.
-- RECONSTRUCTED: verify against live. The body is written from those
-- readers; the station choice, the 24-hour history window and the
-- per-minute grouping of a wake cycle's readings are assumptions.
create or replace function public.get_bundled_dashboard_payload(p_user_id bigint)
returns jsonb
language plpgsql
stable
as $$
declare
    stations jsonb;
    v_area   text;
    sensor   jsonb;
    weather  jsonb;
    fc       jsonb;
    history  jsonb;
begin
    select coalesce(u."ClosestStations", '{}'::jsonb)
      into stations
      from public."UserData" u
     where u."userID" = p_user_id;
    stations := coalesce(stations, '{}'::jsonb);
    v_area := stations ->> 'forecast_area';

    -- Latest reading of each sensor type.
    with latest as (
        select distinct on (sensor_type) sensor_type, data1, created_at
          from public."SensorData"
         order by sensor_type, created_at desc
    )
    select jsonb_build_object(
               'pH',   (select data1 from latest where sensor_type = 'pH'),
               'TDS',  (select data1 from latest where sensor_type = 'TDS'),
               'temp', (select data1 from latest where sensor_type = 'temp'),
               'LUX',  (select data1 from latest where sensor_type = 'LUX'),
               'recorded_at', (select max(created_at) from latest))
      into sensor;

    -- Latest reading per metric, preferring the pond's closest station.
    with latest as (
        select distinct on (metric) metric, station_id, value, recorded_at
          from public.weather_telemetry
         order by metric,
                  (station_id = stations ->> metric) desc nulls last,
                  recorded_at desc
    )
    select jsonb_build_object(
               'air_temp',          (select jsonb_build_object('value', value, 'station_id', station_id, 'recorded_at', recorded_at) from latest where metric = 'air_temp'),
               'rainfall',          (select jsonb_build_object('value', value, 'station_id', station_id, 'recorded_at', recorded_at) from latest where metric = 'rainfall'),
               'wind_speed',        (select jsonb_build_object('value', value, 'station_id', station_id, 'recorded_at', recorded_at) from latest where metric = 'wind_speed'),
               'relative_humidity', (select jsonb_build_object('value', value, 'station_id', station_id, 'recorded_at', recorded_at) from latest where metric = 'relative_humidity'))
      into weather;

    -- Latest forecast of each type; forecast_2hr for the pond's area.
    with latest as (
        select distinct on (wf.forecast_type) wf.forecast_type, wf.payload
          from public.weather_forecasts wf
         order by wf.forecast_type,
                  (wf.area = v_area) desc nulls last,
                  wf.fetched_at desc
    )
    select jsonb_build_object(
               'forecast_2hr',  (select payload from latest where forecast_type = 'forecast_2hr'),
               'forecast_24hr', (select payload from latest where forecast_type = 'forecast_24hr'),
               'outlook_4day',  coalesce((select payload from latest where forecast_type = 'outlook_4day'), '[]'::jsonb),
               'uv_index',      (select payload from latest where forecast_type = 'uv_index'))
      into fc;
    fc := fc || jsonb_build_object(
        'two_hr_forecast', fc -> 'forecast_2hr' ->> 'forecast',
        'rainfall_mm',     weather -> 'rainfall' -> 'value');

    -- Last 24 hours of readings, one entry per wake cycle.
    select coalesce(jsonb_agg(jsonb_build_object(
               'time',  cycle,
               'ph',    ph,
               'tds',   tds,
               'tempC', temp_c,
               'lux',   lux) order by cycle), '[]'::jsonb)
      into history
      from (
        select date_trunc('minute', created_at) as cycle,
               avg(data1) filter (where sensor_type = 'pH')   as ph,
               avg(data1) filter (where sensor_type = 'TDS')  as tds,
               avg(data1) filter (where sensor_type = 'temp') as temp_c,
               avg(data1) filter (where sensor_type = 'LUX' and data1 >= 0) as lux
          from public."SensorData"
         where created_at >= now() - interval '24 hours'
         group by 1
      ) cycles;

    return jsonb_build_object(
        'raw_sensor',        sensor,
        'nea_telemetry',     weather,
        'nea_forecasts',     fc,
        'telemetry_history', history);
end;
$$;

-- Daily trends and intervention markers for the detail graph screen.
-- Keys read by detail_graph_screen.dart and historical_line_chart.dart:
--   daily_trends  [{date, sensor_type, avg_value, min_value, max_value}]
--   interventions [{event_type, timestamp, is_major_reset, ...}]
-- RECONSTRUCTED: verify against live. is_major_reset is written here as
-- a water change of 50 % or more, or any algae scrub; the app only draws
-- those markers more prominently.
create or replace function public.get_historical_graph_payload(p_userid bigint, p_days integer)
returns jsonb
language sql
stable
as $$
    select jsonb_build_object(
        'daily_trends', coalesce((
            select jsonb_agg(jsonb_build_object(
                       'date',        d.record_date,
                       'sensor_type', d.sensor_type,
                       'avg_value',   d.avg_value,
                       'min_value',   d.min_value,
                       'max_value',   d.max_value) order by d.record_date)
              from public.daily_sensor_averages d
             where d.userid = p_userid
               and d.record_date >= (now() at time zone 'UTC')::date - p_days), '[]'::jsonb),
        'interventions', coalesce((
            select jsonb_agg(jsonb_build_object(
                       'id',                 i.id,
                       'event_type',         i.event_type,
                       'timestamp',          i.event_timestamp,
                       'volume_percentage',  i.volume_percentage,
                       'volume_litres',      i.volume_litres,
                       'food_grams',         i.food_grams,
                       'protein_percentage', i.protein_percentage,
                       'algae_method',       i.algae_method,
                       'is_major_reset',     (i.event_type = 'WATER_CHANGE' and coalesce(i.volume_percentage, 0) >= 50)
                                             or i.event_type = 'ALGAE_SCRUB') order by i.event_timestamp)
              from public."pondInterventions" i
             where i."userID" = p_userid
               and i.event_timestamp >= now() - make_interval(days => p_days)), '[]'::jsonb));
$$;
