-- 0005_algae_severity_ratings.sql
--
-- Human algae severity labels from the app's rating card (new feature;
-- the live project does not have this table, checked 2026-10-01). Moved
-- here from the earlier reconstructed baseline, which defined it without
-- it ever being applied. Until this migration is applied, the backend's
-- rating endpoints fail against live.
--
-- green_ratio_at_rating is copied from the frame so the calibration set
-- survives imageTable rows being pruned; image_id is cleared rather than
-- the rating deleted when that happens. severity is one of 'none',
-- 'minor', 'moderate', 'severe' or 'obstruction'
-- (algae_engine.SEVERITY_LEVELS plus the blocked-view flag).
--
-- Only the backend's secret key reads or writes it, so RLS is on with no
-- policies and the default grants to anon and authenticated are revoked.

create table if not exists public.algae_severity_ratings (
    id                    bigint generated by default as identity primary key,
    userid                bigint not null,
    image_id              bigint references public."imageTable" (id) on delete set null,
    image_url             text,
    severity              text not null,
    is_obstructed         boolean not null default false,
    green_ratio_at_rating double precision,
    image_captured_at     timestamptz,
    rated_at              timestamptz not null default now(),
    notes                 text
);

create index if not exists algae_severity_ratings_user_rated_idx
    on public.algae_severity_ratings (userid, rated_at desc);

alter table public.algae_severity_ratings enable row level security;

revoke all on table public.algae_severity_ratings from anon, authenticated;
revoke all on sequence public.algae_severity_ratings_id_seq from anon, authenticated;
