-- 0008_pond_profile.sql
--
-- Effective-dated pond profile (issue #16). Each row is the pond's
-- configuration from effective_from until the next row's effective_from,
-- so a change to the pond (resized, restocked, depth measured) applies
-- from its own time onward and never rewrites what earlier evaluations
-- were computed against. Rows are never updated or deleted by the
-- backend; old rows stay for historical replay.
--
-- Lookup rule (backend, koi/models/profile.py): the profile in force at
-- time t is the row with the latest effective_from <= t; a time before
-- the first row uses the first row. (pond_id, effective_from) is unique,
-- so the lookup is deterministic and periods cannot overlap.
--
-- Time zone: effective_from is timestamptz, an absolute instant. The API
-- accepts ISO 8601 with an offset; a time without one is read as UTC.
-- Nothing here depends on the pond's local day.
--
-- pond_id is UserData."userID", the numeric pond id every other table
-- uses. UserData stays the legacy pond configuration until #67 creates
-- the canonical pond table; #67 repoints this foreign key at it. This
-- table holds configuration only, not ownership (that is
-- UserData.auth_uid, 0007). No cascade on delete, so a pond's history is
-- not removed by deleting its UserData row.
--
-- Units and unknowns:
--   volume_l          litres, > 0, required
--   depth_m           metres, > 0; null = not measured (the evaporation
--                     model then uses its stated default depth)
--   biomass_g         grams of fish, >= 0, required
--   fish_type         free text; null = not given
--   fish_count        >= 0; null = not given
--   tap_tds_ppm       >= 0; null = not given (model default 30 ppm)
--   tap_nitrate_ppm   >= 0; null = not given (model default 0 ppm)
--   aeration          null = not given
--   source            'userdata_seed' (this migration), 'userdata' (the
--                     legacy onboarding write, trigger below), 'api'
--                     (PUT /v1/ponds/{pond}/profile)
--
-- Biomass conversion: UserData.biomass is kilograms. Its only writer is
-- the app's onboarding screen (onboarding_screen.dart sends the sum of
-- count x average weight in kg, "biomass": totalBiomassKg) and its only
-- reader is the backend, which multiplied by 1000 to get grams
-- (koi/storage/base.py, pond_config_from_userdata_row). The seed and the
-- trigger therefore store biomass_g = biomass * 1000. UserData.volume is
-- litres (the onboarding field and every engine read it as litres).
--
-- Seed: one row per UserData pond that has a positive volume and a
-- non-negative biomass, effective from the pond's created_at, depth and
-- the other fields unknown. Ponds without both stay unprofiled, as they
-- were unmodelled before.
--
-- Access: backend only (service role). RLS on with no policies, and the
-- default grants to anon and authenticated revoked. The trigger function
-- is security definer so the app's onboarding upsert into UserData can
-- still record its change here; it is not callable directly.

create table if not exists public.pond_profile (
    id               bigint generated by default as identity primary key,
    pond_id          bigint not null references public."UserData" ("userID") on update cascade,
    effective_from   timestamptz not null,
    volume_l         numeric not null check (volume_l > 0),
    depth_m          numeric check (depth_m > 0),
    biomass_g        numeric not null check (biomass_g >= 0),
    fish_type        text,
    fish_count       integer check (fish_count >= 0),
    tap_tds_ppm      numeric check (tap_tds_ppm >= 0),
    tap_nitrate_ppm  numeric check (tap_nitrate_ppm >= 0),
    aeration         boolean,
    source           text not null default 'api' check (source in ('userdata_seed', 'userdata', 'api')),
    created_at       timestamptz not null default now(),
    constraint pond_profile_pond_effective_key unique (pond_id, effective_from)
);

alter table public.pond_profile enable row level security;

revoke all on table public.pond_profile from anon, authenticated;
revoke all on sequence public.pond_profile_id_seq from anon, authenticated;


insert into public.pond_profile (pond_id, effective_from, volume_l, biomass_g, source)
select u."userID", u.created_at, u.volume, u.biomass * 1000, 'userdata_seed'
from public."UserData" u
where u.volume > 0 and u.biomass >= 0
on conflict (pond_id, effective_from) do nothing;


-- Records a legacy UserData volume or biomass change as a new profile row
-- effective at the time of the write, carrying the other fields over from
-- the profile then in force. Values the profile cannot hold (no volume,
-- no biomass, volume <= 0) are skipped, as the backend skipped them
-- before. A failure here never fails the UserData write: it is reported
-- as a warning and the profile is left as it was.
create or replace function public.record_userdata_profile_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_prev public.pond_profile%rowtype;
begin
    if new.volume is null or new.volume <= 0 or new.biomass is null or new.biomass < 0 then
        return new;
    end if;
    if tg_op = 'UPDATE' and new.volume is not distinct from old.volume
       and new.biomass is not distinct from old.biomass then
        return new;
    end if;
    begin
        select * into v_prev from public.pond_profile
        where pond_id = new."userID" and effective_from <= now()
        order by effective_from desc
        limit 1;

        insert into public.pond_profile (pond_id, effective_from, volume_l, depth_m, biomass_g, fish_type,
                                         fish_count, tap_tds_ppm, tap_nitrate_ppm, aeration, source)
        values (new."userID", now(), new.volume, v_prev.depth_m, new.biomass * 1000, v_prev.fish_type,
                v_prev.fish_count, v_prev.tap_tds_ppm, v_prev.tap_nitrate_ppm, v_prev.aeration, 'userdata')
        on conflict (pond_id, effective_from) do update
            set volume_l = excluded.volume_l, biomass_g = excluded.biomass_g, source = excluded.source;
    exception when others then
        raise warning 'pond_profile not updated for pond %: %', new."userID", sqlerrm;
    end;
    return new;
end;
$$;

revoke all on function public.record_userdata_profile_change() from public, anon, authenticated;

drop trigger if exists "UserData_record_profile_change" on public."UserData";
create trigger "UserData_record_profile_change"
    after insert or update of volume, biomass on public."UserData"
    for each row execute function public.record_userdata_profile_change();
