-- Issue #30: owner test-kit measurements and immutable model comparisons.
-- Measurement fields are nullable: an untested analyte stays unknown.
-- Backend only; kit readings never update engine snapshots or evaluations.
create table public.kit_readings (
    id bigint generated by default as identity primary key,
    -- As pond_profile and camera_config: follow a renumbered pond, and refuse
    -- to delete a pond that has readings rather than drop owner measurements.
    pond bigint not null references public."UserData" ("userID") on update cascade,
    taken_at timestamptz,
    kit text,
    ammonia_mg_l double precision,
    nitrite_mg_l double precision,
    nitrate_mg_l double precision,
    ph double precision,
    kh_dkh double precision,
    notes text,
    estimates jsonb,
    differences jsonb,
    comparison jsonb,
    created_at timestamptz not null default now(),
    constraint kit_readings_values check (
        (ammonia_mg_l is null or ammonia_mg_l >= 0 and ammonia_mg_l < 'Infinity'::float8)
        and (nitrite_mg_l is null or nitrite_mg_l >= 0 and nitrite_mg_l < 'Infinity'::float8)
        and (nitrate_mg_l is null or nitrate_mg_l >= 0 and nitrate_mg_l < 'Infinity'::float8)
        and (ph is null or ph between 0 and 14)
        and (kh_dkh is null or kh_dkh >= 0 and kh_dkh < 'Infinity'::float8)
    )
);
create index kit_readings_pond_time on public.kit_readings (pond, taken_at, id);
alter table public.kit_readings enable row level security;
revoke all on public.kit_readings from anon, authenticated;
grant all on public.kit_readings to service_role;
revoke all on sequence public.kit_readings_id_seq from anon, authenticated;
grant usage, select on sequence public.kit_readings_id_seq to service_role;
