-- Issue #32: per-pond calibration of three model constants, versioned.
--
-- One row per calibration result, never updated: the worker's daily
-- calibration job (koi/worker/poller.py) appends a row when a fit's
-- inputs or value change. The version in force for a parameter at time T
-- is its newest 'fitted' row with effective_from <= T (ties by id), so a
-- rebuild replaying time T uses the version that existed then.
--
-- parameter
--   evaporation_shelter_factor  value: wind shelter factor (default 0.6)
--   water_air_temperature       value: water minus lagged air, degC
--                               (default -1.0); lag_hours: the lag
--   nitrification_rate_scale    value: multiplier on both nitrification
--                               rates (default 1.0)
-- status
--   fitted   value is the fit; sample_count, error and the intervals
--            describe it
--   pending  not enough usable data: value is null, details.reason and
--            sample_count say what is missing; the engines keep their
--            defaults. A pending row never replaces a fitted one.
-- training_from/to is the data the fit used; evaluation_from/to, when
-- present, is a later, separate interval on which error was measured
-- (the temperature fit's error against persistence).
--
-- Backend only: RLS on with no policies, revoked from anon and
-- authenticated, granted to service_role. Existing tables unchanged.
create table public.pond_calibration (
    id bigint generated by default as identity primary key,
    -- As pond_profile and kit_readings: follow a renumbered pond, and
    -- refuse to delete a pond that has calibration history.
    pond_id bigint not null references public."UserData" ("userID") on update cascade,
    parameter text not null check (parameter in (
        'evaporation_shelter_factor', 'water_air_temperature', 'nitrification_rate_scale')),
    status text not null check (status in ('fitted', 'pending')),
    value double precision,
    lag_hours double precision,
    fitted_at timestamptz not null,
    effective_from timestamptz not null,
    sample_count integer not null default 0 check (sample_count >= 0),
    error jsonb,
    training_from timestamptz,
    training_to timestamptz,
    evaluation_from timestamptz,
    evaluation_to timestamptz,
    details jsonb,
    method_version integer not null default 1,
    created_at timestamptz not null default now(),
    constraint pond_calibration_value check (
        status = 'fitted' and value is not null and value > '-Infinity'::float8 and value < 'Infinity'::float8
        or status = 'pending' and value is null),
    constraint pond_calibration_lag check (
        lag_hours is null or lag_hours >= 0 and lag_hours < 'Infinity'::float8),
    constraint pond_calibration_intervals check (
        (training_from is null or training_to is null or training_from <= training_to)
        and (evaluation_from is null or evaluation_to is null or evaluation_from <= evaluation_to)
        and (training_to is null or evaluation_from is null or training_to <= evaluation_from)),
    constraint pond_calibration_json check (
        (error is null or jsonb_typeof(error) = 'object')
        and (details is null or jsonb_typeof(details) = 'object'))
);
create index pond_calibration_in_force on public.pond_calibration (pond_id, parameter, effective_from, id);
alter table public.pond_calibration enable row level security;
revoke all on public.pond_calibration from anon, authenticated;
grant all on public.pond_calibration to service_role;
revoke all on sequence public.pond_calibration_id_seq from anon, authenticated;
grant usage, select on sequence public.pond_calibration_id_seq to service_role;
