-- Issue #36: the notification outbox.
--
-- One row per notification the worker decides to send (koi/notifications.py):
-- a pond's assessment turning red, a lead-time ladder action, a sensor node
-- silent for three expected intervals, a camera frame reporting an
-- obstruction. Rows are written by the poller and delivered later by a
-- sender (the push notification issue); sent_at and error record the
-- outcome, both null while the row is waiting.
--
-- kind               status_red, ladder_action, node_silent, camera_obstructed
-- severity           info, warning, critical
-- title, body        the text shown to the owner
-- data               a jsonb object with the trigger's details
-- dedupe_key         what the row is about (status_red:chemistry,
--                    ladder_action:REACT:2026-10-09, node_silent:sensor, ...)
-- created_at         the worker cycle's time
-- sent_at, error     set by the sender: delivered, or why not
--
-- Writes go through enqueue_notification, which inserts only when the pond
-- has no row with the same dedupe_key created within the given cool-down
-- before p_created_at, so a status that flaps between amber and red does
-- not repeat. The check and the insert are serialised per pond and key by
-- a transaction advisory lock.
--
-- Backend only: RLS on with no policies, table, sequence and function
-- revoked from anon and authenticated, granted to service_role. Existing
-- tables unchanged.
create table public.notification_outbox (
    id bigint generated by default as identity primary key,
    -- As kit_readings: follow a renumbered pond, and refuse to delete a
    -- pond that has notification history.
    pond bigint not null references public."UserData" ("userID") on update cascade,
    kind text not null check (kind in ('status_red', 'ladder_action', 'node_silent', 'camera_obstructed')),
    severity text not null check (severity in ('info', 'warning', 'critical')),
    title text not null check (length(btrim(title)) between 1 and 200),
    body text not null check (length(btrim(body)) between 1 and 2000),
    data jsonb not null default '{}'::jsonb check (jsonb_typeof(data) = 'object'),
    created_at timestamptz not null default now(),
    dedupe_key text not null check (length(dedupe_key) between 1 and 200),
    sent_at timestamptz,
    error text
);
-- The cool-down lookup: newest row of a pond and key.
create index notification_outbox_dedupe on public.notification_outbox (pond, dedupe_key, created_at desc);
-- The sender's queue: rows not yet sent or failed.
create index notification_outbox_pending on public.notification_outbox (pond, created_at, id)
    where sent_at is null and error is null;

alter table public.notification_outbox enable row level security;
revoke all on public.notification_outbox from public, anon, authenticated;
grant select, insert, update, delete on public.notification_outbox to service_role;
revoke all on sequence public.notification_outbox_id_seq from public, anon, authenticated;
grant usage, select on sequence public.notification_outbox_id_seq to service_role;

-- Inserts one outbox row unless the pond already has a row with the same
-- dedupe_key created after p_created_at - p_cooldown_seconds. Returns the
-- stored row, or null when it was suppressed.
create or replace function public.enqueue_notification(
    p_pond bigint,
    p_kind text,
    p_severity text,
    p_title text,
    p_body text,
    p_data jsonb,
    p_dedupe_key text,
    p_created_at timestamptz,
    p_cooldown_seconds integer
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_at timestamptz := coalesce(p_created_at, now());
    v_row public.notification_outbox;
begin
    if p_cooldown_seconds is null or p_cooldown_seconds < 0 then
        raise exception 'enqueue_notification: cool-down must be zero or more seconds'
            using errcode = '22023';
    end if;
    perform pg_advisory_xact_lock(hashtextextended('notification_outbox:' || p_pond || ':' || p_dedupe_key, 0));
    if exists (
        select 1 from public.notification_outbox o
        where o.pond = p_pond and o.dedupe_key = p_dedupe_key
          and o.created_at > v_at - make_interval(secs => p_cooldown_seconds)
    ) then
        return null;
    end if;
    insert into public.notification_outbox (pond, kind, severity, title, body, data, created_at, dedupe_key)
    values (p_pond, p_kind, p_severity, p_title, p_body, coalesce(p_data, '{}'::jsonb), v_at, p_dedupe_key)
    returning * into v_row;
    return to_jsonb(v_row);
end;
$$;

revoke all on function public.enqueue_notification(bigint, text, text, text, text, jsonb, text, timestamptz, integer)
    from public, anon, authenticated;
grant execute on function public.enqueue_notification(bigint, text, text, text, text, jsonb, text, timestamptz, integer)
    to service_role;
